# ----
# Site

title: "[HOW TO?] 설명이 어려운 개발자"
url: "https://bdev.io"
baseurl:
google_analytics_key:
show_full_navigation: true

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /siteicon.png
description: "설명이 힘든 개발자가 설명이 힘든 개발자를 위해 코드로 표현하는법"
author:
  name: KUUWANGE
  email: shellcodesniper@gmail.com
  affilination: Caramella Inc.
  twitter: # twitter username without the @ symbol

# -----
# Build

timezone: Asia/Seoul

permalink: pretty

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

collections:
  docs:
    title: Documentation
    permalink: /:path/
    output: true

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
      image: "https://bdev-s3.s3.ap-northeast-2.amazonaws.com/pics/20221129145508fOASxH_프로필_쿠왕.png"
  -
    scope:
      path: ""
      type: "docs"
    values:
      seo:
        type: Article
      _comments:
        category: Group navigation links with this field
        order: Used to sort links in the navigation
      _options:
        content:
          width: 800
          height: 2000
  -
    scope:
      path: ""
      type: "posts"
    values:
      _comments:
        type: Marks the impact of this release
  -
    scope:
      path: "/whoami"
    values:
      seo:
        type: Person
      _comments:
        type: Who aam I?

# -----------
# CloudCannon

types:
  - minor
  - major
